apiVersion: v2
name: kubevious
description: A Helm chart for Kubevious
type: application
version: 0.5.3
appVersion: 0.5.3
dependencies:
  - name: nginx-ingress
    version: 1.36.0
    repository: https://kubernetes-charts.storage.googleapis.com/